spring:
  data:
    redis:
      host: localhost
      port: 6379
#      username: ${REDIS_USERNAME}
#      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:mysql://localhost:3306/cartdb_dev
    username: root
    password: ankan123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cache:
    type: redis
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org:
      springframework:
        data:
          redis: info
springdoc:
  override-with-generic-response: true
  api-docs:
    path: /api-docs
server:
  port: 8066